# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_article',
            name='feels',
            field=models.IntegerField(choices=[(1, 'yes'), (0, 'no')], verbose_name='Ding or Cai'),
        ),
    ]
